language: python
cache: pip
python:
  - "3.6"
  - "3.6-dev"
  - "nightly"

matrix:
  include:
    - env:
        - TESTING=docs
      before_install:
        - pip install -U sphinx
      script:
        - sphinx-build -nW -q -b html -b linkcheck -d docs/_build/doctrees docs docs/_build/html

before_install:
  - pip install .
  - pip install -U pytest pytest-cov
script:
  - pytest --cov=gidgethub
after_success:
  - bash <(curl -s https://codecov.io/bash)

