language: python
cache: pip
python:
  - "3.6"
  - "3.6-dev"
  - "nightly"

before_install:
  - pip install .
  - pip install -U pytest pytest-cov sphinx
script:
  - pytest --cov=gidgethub
  - sphinx-build -nW -q -b html -b linkcheck -d docs/_build/doctrees docs docs/_build/html
after_success:
  - bash <(curl -s https://codecov.io/bash)

